# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Start Jekyll
email: mayankkhanna98@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A guide to getting started with Jekyll. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:8000" # the base hostname & protocol for your site
twitter_username: mayank_khanna98 
github_username:  khanna98

# Build settings
sass:
  sass_dir: _sass
inlcude: ['pages']
kramdown:
  input: GFM

port: 8000